# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: true
r_check_args: --as-cran --use-valgrind
before_install: sudo apt install -y valgrind

r:
  - devel
  - release
  - oldrel
  - 3.6.2
